labels: ["unconfirmed bug"]
body:
  - type: markdown
    attributes:
      value: |
        > [!IMPORTANT]
        > Please review the [documentation](https://stalw.art/docs/), check the [FAQ](https://stalw.art/docs/faq), and search existing [Discussions](https://github.com/stalwartlabs/stalwart/discussions) and [Issues](https://github.com/stalwartlabs/stalwart/issues?q=sort%3Areactions-desc) before opening a new Discussion.
        >
        > Most reported issues turn out to be configuration problems rather than actual bugs. Starting here helps us triage effectively—if this is confirmed as a bug, we'll create an Issue for tracking.
  - type: markdown
    attributes:
      value: "# Issue Details"
  - type: textarea
    attributes:
      label: Issue Description
      description: |
        Provide a detailed description of the issue. Include relevant context such as your configuration, environment, and any recent changes that might have led to the issue.
      placeholder: |
        When trying to send an email via SMTP, the connection is accepted but the message is rejected with error 550.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: |
        Describe how you expect Stalwart to behave in this situation. Include any relevant documentation links.
      placeholder: |
        The email should be accepted and delivered to the recipient's mailbox.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Actual Behavior
      description: |
        Describe how Stalwart actually behaves in this situation. If it is not immediately obvious how the actual behavior differs from the expected behavior described above, please mention the deviation specifically.
      placeholder: |
        The email is rejected with error: "550 5.7.1 Relay access denied"
    validations:
      required: false
  - type: textarea
    attributes:
      label: Reproduction Steps
      description: |
        Provide a detailed set of step-by-step instructions for reproducing this issue.
      placeholder: |
        1. Configure Stalwart with the attached configuration.
        2. Attempt to send an email from user@example.com to external@domain.com.
        3. Observe the 550 error in the SMTP session.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Relevant Log Output
      description: |
        Please copy and paste any relevant log output. Set logging level to `trace` if you can't find any relevant errors in the log.
      render: shell
  - type: dropdown
    attributes:
      label: Stalwart Version
      description: What version of Stalwart are you running?
      options:
        - v0.15.x
        - v0.14.x
        - v0.13.x
        - v0.12.x or lower
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Installation Method
      description: How did you install Stalwart?
      options:
        - Docker
        - Binary (Linux)
        - Binary (macOS)
        - Binary (FreeBSD)
        - Binary (Windows)
        - NixOS
        - Built from source
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Database Backend
      description: What database are you using for the data store?
      options:
        - RocksDB
        - FoundationDB
        - PostgreSQL
        - MySQL
        - SQLite
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Blob Storage
      description: What blob storage are you using?
      options:
        - RocksDB
        - FoundationDB
        - PostgreSQL
        - MySQL
        - SQLite
        - Filesystem
        - S3-compatible
        - Azure
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Search Engine
      description: What search engine are you using?
      options:
        - Internal
        - Meilisearch
        - Elasticsearch
        - PostgreSQL
        - MySQL
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Directory Backend
      description: Where is your directory/user database located?
      options:
        - Internal
        - SQL
        - LDAP
        - OIDC
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional Context
      description: |
        Add any other context about the problem here. This could include:
        - Client software and versions (Thunderbird, Apple Mail, K-9, etc.)
        - Proxy or reverse proxy configuration (nginx, Traefik, etc.)
        - Network setup (NAT, firewall rules, etc.)
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        # Acknowledgements
        > [!TIP]
        > Use these links to review existing [Discussions](https://github.com/stalwartlabs/stalwart/discussions) and [Issues](https://github.com/stalwartlabs/stalwart/issues?q=sort%3Areactions-desc).
  - type: checkboxes
    attributes:
      label: "I acknowledge that:"
      options:
        - label: I have reviewed the documentation and FAQ and confirm that my issue is NOT addressed there.
          required: true
        - label: I have searched the Stalwart repository (both open and closed Discussions and Issues) and confirm this is not a duplicate.
          required: true
        - label: I have set the logging level to `trace` and included relevant log output if applicable.
          required: false
        - label: I agree to follow the project's [Code of Conduct](https://github.com/stalwartlabs/.github/blob/main/CODE_OF_CONDUCT.md).
          required: true
