name: Confirmed Bug Report
description: Only for issues that have been discussed and confirmed as bugs in GitHub Discussions.
labels: ["bug"]
title: "🪲: "
body:
  - type: markdown
    attributes:
      value: |
        > [!IMPORTANT]
        > This template is **only** for issues that have already been discussed and confirmed as bugs in the [Discussions](https://github.com/stalwartlabs/stalwart/discussions) section.
        >
        > If you haven't had your issue confirmed yet, please [start a Discussion](https://github.com/stalwartlabs/stalwart/discussions/new?category=issue-triage) first.
  - type: input
    attributes:
      label: Discussion Link
      description: Provide the link to the Discussion where this issue was confirmed as a bug.
      placeholder: https://github.com/stalwartlabs/stalwart/discussions/1234
    validations:
      required: true
  - type: textarea
    attributes:
      label: Bug Summary
      description: Brief summary of the confirmed bug.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional Information
      description: |
        Include any additional information not covered in the original Discussion, such as new findings, workarounds discovered, or updated reproduction steps.
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: Confirmation
      options:
        - label: This issue was discussed and confirmed as a bug in the linked Discussion.
          required: true
        - label: I have included the link to the Discussion above.
          required: true
